server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
         git:
           url: http://172.20.3.121:7070/chenxiaoliang/cloud.git
           search-paths:
             - springcloud-config
      label: master
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#设置与eureka servie 交互的地址查询服务以及注册服务的地址
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
