server:
  port: 3346
  p: 1222
spring:
  application:
    name: config-client22222

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#设置与eureka servie 交互的地址查询服务以及注册服务的地址
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
